language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
branches:
  except:
    - php-52
before_script: composer install && wget https://scrutinizer-ci.com/ocular.phar
script: "./vendor/bin/phpunit --coverage-clover=coverage.clover && php ocular.phar code-coverage:upload --format=php-clover coverage.clover && ./vendor/bin/phpcs -n src/"
